security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN
        ROLE_PRES: ROLE_PRES

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
            main:
                pattern: ^/.*
                anonymous: true
                form_login:
                    login_path: /login
                    use_forward: false
                    check_path: /login_check
                    post_only:   true
                    default_target_path: /
                    success_handler: success_handlers

                logout:
                    path:   /logout
                    target: /login
                #logout:       true
                #anonymous:    true



    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: [ROLE_ADMIN,ROLE_SUPER_ADMIN,ROLE_PRES] }
        - { path: ^/admin_accueil, role: [ROLE_ADMIN,ROLE_SUPER_ADMIN,ROLE_PRES] }


